config/routes.rb
Rails.application.routes.draw do

  namespace :api do
      # get 'tweets/:id/:id', to: '/api/tweets#show'
      resources :tweets, path: :news, only: [:index, :show, :create, :destroy]
      # get '/api/tweets/*date', :controller => 'api/tweets', :action => 'index'
    end
  

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  namespace :admin do 
    resources :users do
      resources :tweets
    end
  end
  
  namespace :admin do 
    resources :users do
      resources :likes
    end
  end
  
  namespace :admin do 
    resources :users do
      resources :friends
    end
  end
  
  
  resources :tweets do
    resources :likes
  end
  
  
  get '/tweets/hashtag/:name', to:'tweets#hashtags'

  # resources :users do		
  #   member do		
  #     get :following, :followers		
  #   end		
  # end		


  # resources :users
  
  #, only: [:profile] do
  # get 'profile'
  #end 

  #get 'home/index'
  devise_for :users, controllers: { registrations: 'users/registrations' }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "home#index"
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user
  has_many :likes, dependent: :destroy
  validates :tweet, presence: true

  has_many :taggings, dependent: :destroy
  has_many :tags, through: :taggings
  
  scope :tweets_for_me, -> {where(tweets.user_id = current_user.friends.followed_id)}



  after_create do
    tweet = Tweet.find_by(id: self.id)
    hashtags = self.tweet.scan(/#\w+/)
    hashtags.uniq.map do |hashtag|
      tag = Tag.find_or_create_by(name: hashtag.downcase.delete('#'))
      tweet.tags << tag
    end

  end

end

app/controllers/api/tweets_controller.rb
module Api
    
      class TweetsController < ApiController
        include ActionController::HttpAuthentication::Basic::ControllerMethods
        http_basic_authenticate_with name: "hello", password: "world", except: :index
        before_action :set_tweet, only: [:show, :edit, :update, :destroy]
  # before_action :authenticate_user!
  
  
  
  # GET /tweets
  # GET /tweets.json
  def index
    @tweets = Tweet.last(50).reverse

    
  end

  # GET /tweets/1
  # GET /tweets/1.json
  def show
    @tweet = Tweet.find(params[:id])
    
  end

  def hashtags 
    tag = Tag.find_by(name: params[:name])
    @tweets = tag.tweets
  end



  # GET /tweets/new
  def new
    @tweet = Tweet.new
    render json: @tweet
  end

  # GET /tweets/1/edit
  def edit
  end

  # POST /tweets
  # POST /tweets.json
  def create
    @tweet = Tweet.new(tweet_params)
    # @tweet.user_id = current_user.id

    respond_to do |format|
      if @tweet.save
        # format.html { redirect_to root_path, notice: 'Tweet was successfully created.' }
        format.json { render :show, status: :created, location: @tweet }
      else
        # format.html { render :new }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tweets/1
  # PATCH/PUT /tweets/1.json
  def update
    respond_to do |format|
      if @tweet.update(tweet_params)
        format.html { redirect_to root_path, notice: 'Tweet was successfully updated.' }
        format.json { render :show, status: :ok, location: @tweet }
      else
        format.html { render :edit }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tweets/1
  # DELETE /tweets/1.json
  def destroy
    @tweet.destroy
    respond_to do |format|
      format.html { redirect_to tweets_url, notice: 'Tweet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tweet
      @tweet = Tweet.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def tweet_params
      params.require(:tweet).permit(:tweet, :user_id)
    end
 

      end
    
  end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :set_tweet, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  
  
  
  # GET /tweets
  # GET /tweets.json
  def index
    
    if params[:tweet].present?
      @tweets = Tweet.where('tweet like ?', "%#{params[:tweet]}%")
    else
      @tweets = Tweet.all
    end
  end

  # GET /tweets/1
  # GET /tweets/1.json
  def show
  end

  def hashtags 
    tag = Tag.find_by(name: params[:name])
    @tweets = tag.tweets
  end



  # GET /tweets/new
  def new
    @tweet = Tweet.new
  end

  # GET /tweets/1/edit
  def edit
  end

  # POST /tweets
  # POST /tweets.json
  def create
    @tweet = Tweet.new(tweet_params.merge(user: current_user))
    # @tweet.user_id = current_user.id

    respond_to do |format|
      if @tweet.save
        format.html { redirect_to root_path, notice: 'Tweet was successfully created.' }
        format.json { render :show, status: :created, location: @tweet }
      else
        format.html { render :new }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tweets/1
  # PATCH/PUT /tweets/1.json
  def update
    respond_to do |format|
      if @tweet.update(tweet_params)
        format.html { redirect_to root_path, notice: 'Tweet was successfully updated.' }
        format.json { render :show, status: :ok, location: @tweet }
      else
        format.html { render :edit }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tweets/1
  # DELETE /tweets/1.json
  def destroy
    @tweet.destroy
    respond_to do |format|
      format.html { redirect_to tweets_url, notice: 'Tweet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tweet
      @tweet = Tweet.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def tweet_params
      params.require(:tweet).permit(:tweet)
    end
   
end

app/helpers/tweets_helper.rb
module TweetsHelper
    def render_with_hashtags(tweet)
        tweet.gsub(/#\w+/){|word| link_to word, "/tweets/hashtag/#{word.downcase.delete('#')}"}.html_safe
    end 

end

app/views/tweets/_form.html.erb
<%= form_with(model: tweet, local: true) do |form| %>
  <% if tweet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tweet.errors.count, "error") %> prohibited this tweet from being saved:</h2>

      <ul>
        <% tweet.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :tweet %>
    <%= form.text_field :tweet %>
  </div>

  
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/tweets/edit.html.erb
<h1>Editing Tweet</h1>

<%= render 'form', tweet: @tweet %>

<%= link_to 'Show', @tweet %> |
<%= link_to 'Back', tweets_path %>

app/views/tweets/hashtags.html.erb
<p id="notice"><%= notice %></p>



<h1>Tweets</h1>

<table>
  <thead>
    <tr>
      <th>Tweet</th>
      <th>User</th>
      <th>Likes</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tweets.each do |tweet| %>
      <tr>
        <td><%= render_with_hashtags(tweet.tweet) %></td>
        
        <td><%= tweet.user_id %></td>
        <td><%= tweet.likes.count %></td>
        <td><%= link_to 'Show', tweet %></td>
        <td><%= link_to 'Edit', edit_tweet_path(tweet) %></td>
        <td><%= link_to 'Destroy', tweet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tweet', new_tweet_path %>

app/views/tweets/index.html.erb
<p id="notice"><%= notice %></p>



<h1>Tweets</h1>

<table>
  <thead>
    <tr>
      <th>Tweet</th>
      <th>User</th>
      <th>Likes</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tweets.each do |tweet| %>
      <tr>
        <td><%= tweet.tweet %></td>
        <td><%= tweet.user_id %></td>
        <td><%= tweet.likes.count %></td>
        <td><%= link_to 'Show', tweet %></td>
        <td><%= link_to 'Edit', edit_tweet_path(tweet) %></td>
        <td><%= link_to 'Destroy', tweet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tweet', new_tweet_path %>

app/views/tweets/new.html.erb
<h1>New Tweet</h1>

<%= render 'form', tweet: @tweet %>

<%= link_to 'Back', tweets_path %>

app/views/tweets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Tweet:</strong>
  <%= @tweet.tweet %>
</p>

<p>
  <strong>User:</strong>
  <%= @tweet.user %>
</p>

<%= link_to 'Edit', edit_tweet_path(@tweet) %> |
<%= link_to 'Back', root_path %>

<p><%= @tweet.likes.count %> <%= (@tweet.likes.count) == 1 ? 'Like' : 'Likes'%></p>


<% same_user_tweet = @tweet.user_id == current_user.id %>
<% if same_user_tweet %>
  <% else %>
    <% pre_like = @tweet.likes.find { |like| like.user_id == current_user.id} %>
    <% if pre_like %>
      <%= button_to 'Unlike', tweet_like_path(@tweet, pre_like), method: :delete %>
    <% else %>
      <%= button_to 'Like', tweet_likes_path(@tweet), method: :post %>
    <% end %>
  <% end %>