config/routes.rb
Rails.application.routes.draw do

  namespace :api do
      # get 'tweets/:id/:id', to: '/api/tweets#show'
      resources :tweets, path: :news, only: [:index, :show, :create, :destroy]
      # get '/api/tweets/*date', :controller => 'api/tweets', :action => 'index'
    end
  

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  namespace :admin do 
    resources :users do
      resources :tweets
    end
  end
  
  namespace :admin do 
    resources :users do
      resources :likes
    end
  end
  
  namespace :admin do 
    resources :users do
      resources :friends
    end
  end
  
  
  resources :tweets do
    resources :likes
  end
  
  
  get '/tweets/hashtag/:name', to:'tweets#hashtags'

  # resources :users do		
  #   member do		
  #     get :following, :followers		
  #   end		
  # end		


  # resources :users
  
  #, only: [:profile] do
  # get 'profile'
  #end 

  #get 'home/index'
  devise_for :users, controllers: { registrations: 'users/registrations' }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "home#index"
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  
  def index
    @tweets = Tweet.all
  
  if params[:tweet].present?
    @tweets = Tweet.where('tweet like ?', "%#{params[:tweet]}%").order('created_at DESC').page(params[:page])
  else
    
    @tweets = Tweet.order('created_at DESC').page(params[:page])
  end

end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

 <div>
  <% @tweets.each do |tweet| %>
    <tr>
      <h1></h1>
      <h2><td><%= tweet.user %> </td></h2>
      <h2> <td><%= render_with_hashtags(tweet.tweet) %></td></h2>
      <h3><td><%= link_to tweet.created_at, tweet_path(tweet.id)%></td></h3>
      <h2><td><%= distance_of_time_in_words(tweet.created_at, Time.now) %></td></h2>
      <h3> Likes <td><%= tweet.likes.count %></td></h3>
    </tr>
  <% end %>
</div>
 
<%= link_to 'New Tweet', new_tweet_path(@user) %>

<div class="row">
  <div class="col-md-8 offset-md-2">
    <%= paginate @tweets %>
  </div>
</div>